package com.amazon.aws.am2.appmig.estimate.bedrock;

import com.amazon.aws.am2.appmig.estimate.CodeMetaData;
import com.amazon.aws.am2.appmig.estimate.Plan;

/**
 * Test class to verify the dynamic context generation using Bedrock.
 */
public class BedrockContextTest {
    
    public static void main(String[] args) {
        // Create a sample WebLogic code snippet
        String weblogicCode = "private static final AuthenticatedSubject KERNEL_ID = (AuthenticatedSubject)AccessController.doPrivileged(PrivilegedActions.getKernelIdentityAction());";
        
        // Create code metadata
        CodeMetaData codeMetaData = new CodeMetaData(10, weblogicCode);
        
        // Create a plan
        Plan plan = new Plan();
        plan.setComplexity("major");
        
        // Create a test version of the recommendation service
        BedrockRecommendationService service = new BedrockRecommendationService() {
            @Override
            protected String invokeBedrockModel(String prompt) {
                // For context analysis prompt
                if (prompt.contains("analyze the following Java code snippet")) {
                    System.out.println("===== CONTEXT ANALYSIS PROMPT =====");
                    System.out.println(prompt);
                    System.out.println("==================================");
                    
                    // Return a mock context analysis response
                    return "CODE CONTEXT:\n" +
                           "This code is using WebLogic-specific security APIs. The code is creating a reference to the WebLogic kernel identity " +
                           "through the AuthenticatedSubject class and PrivilegedActions utility. This is a common pattern in WebLogic applications " +
                           "that need to perform privileged operations. These classes are proprietary to WebLogic and will need to be replaced with " +
                           "standard Java security mechanisms when migrating to Tomcat.\n\n" +
                           "FILE CONTEXT:\n" +
                           "This code is likely part of a security management class in a WebLogic application. The file probably contains imports for " +
                           "weblogic.security.* packages and may include other security-related methods that use this KERNEL_ID for performing " +
                           "privileged operations within the WebLogic server environment.";
                }
                // For recommendation prompt
                else {
                    System.out.println("===== RECOMMENDATION PROMPT =====");
                    System.out.println(prompt);
                    System.out.println("=================================");
                    
                    // Return a mock recommendation response
                    return "Migration Recommendation for WebLogic Security Code\n\n" +
                           "This is a mock recommendation response that would be generated by Bedrock.";
                }
            }
        };
        
        // Generate a recommendation (this will print both prompts)
        service.generateRecommendation(codeMetaData, plan, "WebLogic", "Tomcat");
        
        System.out.println("\nTest completed successfully!");
    }
}